apiVersion: v1
kind: PersistentVolume
metadata:
  name: xtreme-media-pv
spec:
  capacity:
    storage: {{ .Values.media.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.media.storageClass }}
  nfs:
    server: {{ .Values.media.nfsServer }}
    path: {{ .Values.media.nfsPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xtreme-media-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.media.storageClass }}
  resources:
    requests:
      storage: {{ .Values.media.size }}
  volumeName: xtreme-media-pv
